// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CityFragment: typeof import('./src/components/city-fragment/city-fragment.vue')['default']
    CopyrightFooter: typeof import('./src/components/copyright-footer/copyright-footer.vue')['default']
    DisplayTemperature: typeof import('./src/components/display-temperature/display-temperature.vue')['default']
    FlexBox: typeof import('./src/components/flex-box/flex-box.vue')['default']
    HeaderBar: typeof import('./src/components/header-bar/header-bar.vue')['default']
    HoursWeatherInfo: typeof import('./src/components/hours-weather-info/hours-weather-info.vue')['default']
    HoursWeatherInfoItem: typeof import('./src/components/hours-weather-info-item/hours-weather-info-item.vue')['default']
    RecentWeatherBtn: typeof import('./src/components/recent-weather-btn/recent-weather-btn.vue')['default']
    RecentWeatherInfo: typeof import('./src/components/recent-weather-info/recent-weather-info.vue')['default']
    RecentWeatherInfoItem: typeof import('./src/components/recent-weather-info-item/recent-weather-info-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryWeatherInfo: typeof import('./src/components/summary-weather-info/summary-weather-info.vue')['default']
    SummaryWeatherInfoItem: typeof import('./src/components/summary-weather-info-item/summary-weather-info-item.vue')['default']
    SunInfo: typeof import('./src/components/sun-info/sun-info.vue')['default']
    TemperatureTextBox: typeof import('./src/components/temperature-text-box/temperature-text-box.vue')['default']
    TipBox: typeof import('./src/components/tip-box/tip-box.vue')['default']
    TipBoxItem: typeof import('./src/components/tip-box-item/tip-box-item.vue')['default']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VideoForecast: typeof import('./src/components/video-forecast/video-forecast.vue')['default']
    WeatherBg: typeof import('./src/components/weather-bg/weather-bg.vue')['default']
  }
}

export {}
